/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthRedirect: typeof import('./../src/components/Auth/Redirect.vue')['default']
    CommonFooter: typeof import('./../src/components/common/Footer.vue')['default']
    DarkSwitcher: typeof import('./../src/components/DarkSwitcher.vue')['default']
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElContainer: typeof import('element-plus/lib')['ElContainer']
    ElDivider: typeof import('element-plus/lib')['ElDivider']
    ElMain: typeof import('element-plus/lib')['ElMain']
    HeartbeatBar: typeof import('./../src/components/HeartbeatBar.vue')['default']
    IconCarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    IconCarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    IconCarbonHome: typeof import('~icons/carbon/home')['default']
    IconCarbonVirtualPrivateCloud: typeof import('~icons/carbon/virtual-private-cloud')['default']
    IconCarbonWarning: typeof import('~icons/carbon/warning')['default']
    Navbar: typeof import('./../src/components/Navbar.vue')['default']
    Progress: typeof import('./../src/components/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WithNavbar: typeof import('./../src/components/WithNavbar.vue')['default']
  }
}
