/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthRedirect: typeof import('./../src/components/Auth/Redirect.vue')['default']
    CircleStatus: typeof import('./../src/components/CircleStatus.vue')['default']
    CommonFooter: typeof import('./../src/components/common/Footer.vue')['default']
    DarkSwitcher: typeof import('./../src/components/DarkSwitcher.vue')['default']
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElContainer: typeof import('element-plus/lib')['ElContainer']
    ElDivider: typeof import('element-plus/lib')['ElDivider']
    ElMain: typeof import('element-plus/lib')['ElMain']
    ElSlider: typeof import('element-plus/lib')['ElSlider']
    IconCarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    IconCarbonCircleFilled: typeof import('~icons/carbon/circle-filled')['default']
    IconCarbonHome: typeof import('~icons/carbon/home')['default']
    IconCarbonWarning: typeof import('~icons/carbon/warning')['default']
    Monitor: typeof import('./../src/components/Monitor/index.vue')['default']
    MonitorBeatRulesResult: typeof import('./../src/components/Monitor/BeatRulesResult.vue')['default']
    MonitorBlock: typeof import('./../src/components/Monitor/Block.vue')['default']
    MonitorEndpoint: typeof import('./../src/components/Monitor/Endpoint.vue')['default']
    MonitorList: typeof import('./../src/components/Monitor/List.vue')['default']
    Navbar: typeof import('./../src/components/Navbar.vue')['default']
    Progress: typeof import('./../src/components/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SizeSlider: typeof import('./../src/components/SizeSlider.vue')['default']
    WithNavbar: typeof import('./../src/components/WithNavbar.vue')['default']
  }
}
